version: "3.7"

networks:
  diverge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  app:
    build: .
    container_name: app-1
    restart: always
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
    ports:
      - "8089:8080"
    networks:
      diverge_network:
        ipv4_address: 172.30.2.3
  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=example"
      - "TZ=Asia/Shanghai"
    ports:
      - "3307:3306"
    networks:
      diverge_network:
        ipv4_address: 172.30.1.3
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/my.cnf
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      diverge_network:
        ipv4_address: 172.30.0.3