version: "3.7"

networks:
  diverge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  app:
    build: .
    container_name: app-1
    restart: always
    volumes:
      - ./conf:/conf
      - ./logs:/logs
      - ./templates:/templates
    ports:
      - "8080:8080"
    network_mode: host